jobs:
  release:
    runs-on: ubuntu-latest
    if: contains(github.ref_name, 'stable')
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: mvn clean package
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: "Minecraft DiscordWhitelistPort ${{ github.ref_name }}"
          artifacts: "target/*.jar"
          draft: false
          prerelease: false
